Repository JoshKarpel/dask-chtc, pull requests merged in 2020-07, with the labels that each got.

#7 Packaging and basic configurability
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  LICENSE
  README.md
  dask_chtc.py
  dask_chtc/__init__.py
  dask_chtc/cli.py
  dask_chtc/cluster.py
  dask_chtc/config.py
  dask_chtc/entrypoint.sh
  dask_chtc/jobqueue-chtc.yaml
  dask_chtc/version.py
  demo/demo.ipynb
  demo/demo.py
  docker/worker/Dockerfile
  docker/worker/logging.yaml
  entrypoint.sh
  mypy.ini
  pyproject.toml
  setup.cfg
  setup.py
  test.py
  tests/__init__.py
  tests/ci.sh
  tests/conftest.py
  tests/test_cluster_args.py
  tests/test_entrypoint.py
  tests/test_version.py
Labels: enhancement

#10 Add CLI command to launch a Jupyter notebook as a local universe job
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  dask_chtc/cli.py
  dask_chtc/cluster.py
  mypy.ini
  pyproject.toml
  setup.cfg
Labels: enhancement

#12 Add Sphinx/RTD docs
  .gitignore
  .readthedocs.yml
  README.md
  dask_chtc/cli.py
  dask_chtc/cluster.py
  docs/Makefile
  docs/make.bat
  docs/source/api.rst
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/ports.rst
  pyproject.toml
  setup.cfg
  tests/test_yaml.py
Labels: documentation, enhancement

#11 Random port selection
  dask_chtc/cluster.py
  pyproject.toml
  setup.cfg
Labels: enhancement, networking

#16 Getting Started docs
  dask_chtc/cli.py
  dask_chtc/cluster.py
  docs/source/_static/dashboard-port.png
  docs/source/example.ipynb
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/jupyter.rst
  docs/source/networking.rst
  docs/source/ports.rst
Labels: documentation, enhancement

#17 Add a docs page for building Docker images
  docs/source/docker.rst
  docs/source/index.rst
Labels: documentation, enhancement

#20 Use TLS for all communications
  dask_chtc/__init__.py
  dask_chtc/cluster.py
  dask_chtc/entrypoint.sh
  dask_chtc/security.py
  pyproject.toml
  setup.cfg
Labels: enhancement, networking, security

#30 Add a --force option to jupyter stop
  dask_chtc/cli.py
  docs/source/index.rst
  docs/source/troubleshooting.rst
Labels: bug, jupyter

#28 DOC: adapts documentation for first-time users
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  dask_chtc/cli.py
  docs/source/example.ipynb
  docs/source/jupyter.rst
Labels: documentation, enhancement, jupyter

#32 Add docs on configuration options
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  dask_chtc/jobqueue-chtc.yaml
  docs/source/configuration.rst
  docs/source/index.rst
Labels: documentation, enhancement

#33 Security for client/cluster created by lab extension
  dask_chtc/cluster.py
  docs/source/_static/labextension.png
  docs/source/api.rst
  docs/source/configuration.rst
Labels: bug, security
